export default [
  {
    id: 1,
    title: 'The sprint swimmeris',
    description: 'The sprint swimmeris',
    coverImg: 'pexels-guduru-ajay-bhargav-863988.jpg',
    location: 'USA',
    openSpots: 6,
    Region: 'US',
  },
   {
    id: 2,
    title: 'Rugby',
    description: 'Rugby',
    price: 280,
    coverImg: 'pexels-pixabay-2207.jpg',
    location: 'Africa',
    openSpots: 3,
    Region: 'Africa',
  },
   {
    id: 2,
    title: 'Rugby',
    description: 'Rugby',
    price: 280,
    coverImg: 'pexels-pixabay-2207.jpg',
    location: 'Africa',
    openSpots: 3,
    Region: 'Africa',
  },
   
   
   
   {
    id: 2,
    title: 'Rugby',
    description: 'Rugby',
    price: 280,
    coverImg: 'pexels-pixabay-2207.jpg',
    location: 'Africa',
    openSpots: 3,
    Region: 'Africa',
  },
  {
    id: 3,
    title: '..',
    description: '',
    price: 90,
    coverImg: 'pexels-pixabay-235922.jpg',
    location: 'Africa',
    openSpots: 10,
    Region: 'Africa',
  },
  {
    id: 4,
    title: '..',
    description: '',
    price: 210,
    coverImg: 'pexels-pixabay-262506.jpg',
    location: 'Africa',
    openSpots: 7,
    Region: 'Africa',
  },
]